#!/bin/bash
export FLASK_ENV=development
FLASK_ENV=development
export FLASK_APP=app
FLASK_APP=app
flask run --host localhost --port 8000

# pkill -f gunicorn
# gunicorn -b localhost:8000 -w 4 -D hello:app
# gunicorn -b localhost:8000 -w 4 -D app:app
